# Generated by Django 2.1.2 on 2018-11-01 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadslides',
            name='c_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CMS.course'),
            preserve_default=False,
        ),
    ]
