# Generated by Django 2.1.2 on 2018-11-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logged',
            name='sem_id',
            field=models.IntegerField(default=0),
        ),
    ]
