# Generated by Django 2.1.2 on 2018-11-01 16:25

import CMS.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Querytoadmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('query', models.CharField(max_length=300)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=45, null=True)),
                ('modified_at', models.DateField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=45, null=True)),
                ('a_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CMS.college_admin')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS.student')),
            ],
        ),
        migrations.CreateModel(
            name='UploadSlides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic', models.CharField(max_length=20)),
                ('readings', models.CharField(max_length=50)),
                ('docfile', models.FileField(upload_to=CMS.models.get_upload_path)),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS.faculty')),
            ],
        ),
        migrations.RemoveField(
            model_name='query',
            name='a_id',
        ),
        migrations.AddField(
            model_name='answerqueryadmin',
            name='subject',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='query',
            name='f_id',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='CMS.faculty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='query',
            name='subject',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='query',
            name='query',
            field=models.CharField(max_length=300),
        ),
    ]
