# Generated by Django 2.1.2 on 2018-11-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0002_auto_20181101_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='ph_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='sem_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
