# Generated by Django 2.1.2 on 2018-11-10 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0002_remove_student_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='registeredcourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.CharField(max_length=100)),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS.student')),
            ],
        ),
    ]
