# Generated by Django 2.1.2 on 2018-11-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0002_uploadslides_c_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadslides',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadslides',
            name='created_by',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='uploadslides',
            name='modified_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadslides',
            name='modified_by',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='college_admin',
            name='apswd',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='fpswd',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='spswd',
            field=models.CharField(max_length=100),
        ),
    ]
