# Generated by Django 2.1.2 on 2018-11-02 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0003_auto_20181102_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificationsfromadmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('query', models.CharField(max_length=300)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=45, null=True)),
                ('modified_at', models.DateField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=45, null=True)),
                ('a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS.college_admin')),
            ],
        ),
        migrations.CreateModel(
            name='Notificationsfromfaculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('query', models.CharField(max_length=300)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=45, null=True)),
                ('modified_at', models.DateField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=45, null=True)),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS.faculty')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS.student')),
            ],
        ),
        migrations.AddField(
            model_name='query',
            name='student_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='querytoadmin',
            name='student_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
