# Generated by Django 2.1.2 on 2018-12-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0003_auto_20181209_1815'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admintoadmin',
            new_name='QuerytoAdmin',
        ),
    ]
