# Generated by Django 2.1.2 on 2018-11-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0003_auto_20181101_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='ph_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='courses',
            field=models.CharField(max_length=100),
        ),
    ]
