# Generated by Django 2.1.2 on 2018-12-09 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0005_auto_20181209_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='admin',
            new_name='query',
        ),
    ]
