# Generated by Django 2.1.2 on 2018-12-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0006_auto_20181209_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsfromfaculty',
            name='s_id',
            field=models.IntegerField(),
        ),
    ]
