from django.urls import path
from django.conf.urls import include,url             
from . import views

urlpatterns = [
    url(r'^$',views.dashboard,name = "index"),
    url(r'^homepage/',views.dashboard,name = "homepage"),
    url(r'^about',views.About,name = 'about'),
    url(r'^aca1',views.Aca1,name = 'aca1'),
    url(r'^aca2',views.Aca2,name = 'aca2'),
    url(r'^contact',views.Contact,name = 'contact'),
    url(r'^facultylogin',views.facultylogin,name = 'facultylogin'),
    url(r'^adminlogin',views.adminlogin,name = 'adminlogin'),
    url(r'^trackattendance',views.trackattendance,name = "trackattendance"),
    url(r'^trackacademicprogress',views.trackacademicprogress,name = "trackacademicprogress"),
    url(r'^login1$',views.login1,name="login1"),
    url(r'^login2$',views.login2,name="login2"),
    url(r'^answerqueries',views.answerqueries,name ="answerqueries"),
    url(r'^studenthome',views.studenthome,name = 'studenthome'),
    url(r'^studentleave',views.studentleave,name = "studentleave"),
    url(r'^studentprofile',views.studentprofile,name  = "studentprofile"),
    url(r'^leavesubmit',views.leavesubmit,name ="leavesubmit"),
    url(r'^studentlogin',views.studentlogin,name = "studentlogin"),
    url(r'^facultylogin',views.facultylogin,name = "facultylogin"),
    url(r'^facultyhome',views.facultyhome,name =  "facultyhome"),
    url(r'^teaching/IR',views.teachingcourse1,name = 'IR'),
    url(r'^teaching/PC',views.teachingcourse2,name = 'PC'),
    url(r'^postanswers',views.postanswers,name = "postanswers"),
    url(r'^details',views.details,name = "details"),
    url(r'^queries',views.queries,name ="queries"),
    #url(r'^register',views.trackacademicprogress),
    url(r'^talks',views.talks,name ="talks"),
    url(r'^teaching',views.teaching,name ="teaching"),
    url(r'^adminmakequery',views.adminmakequery,name ="adminmakequery"),
    url(r'^facultymakequery',views.facultymakequery,name ="facultymakequery"),
    url(r'^facultyprofile',views.facultyprofile,name  = "facultyprofile"),
    url(r'^login3$',views.login3,name="login3"),
    url(r'^adminhome',views.adminhome,name ="adminhome"),
    url(r'^addevents',views.addevents,name ="addevents"),
    url(r'^addfaculty',views.addfaculty,name ="addfaculty"),
    url(r'^addstudent',views.addstudent,name ="addstudent"),
    url(r'^adminanswerqueries',views.adminanswerqueries,name="adminanswerqueries"),
    url(r'^adminevents',views.adminevents,name ="adminevents"),
    url(r'^adminfaculty',views.adminfaculty,name ="adminfaculty"),
    url(r'^adminlogin',views.adminlogin,name ="adminlogin"),
    url(r'^adminprofile',views.adminprofile,name ="adminprofile"),
    url(r'^adminqueries',views.adminqueries,name ="adminqueries"),
    url(r'^adminstudents',views.adminstudents,name ="adminstudents"),
    url(r'^callback/(?P<token>.+)$',views.callback,name='callback'),
]